version: '3.2'
services:
  # this is the web application we are going to test
  sentimentalyzer:
    build: ../
    environment:
      - PORT=8123

  # Cypress container
  cypress:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
    container_name: cypress-image

    depends_on:
      - sentimentalyzer
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://sentimentalyzer:8123
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - ./:/e2e
